version: '3.9'
services:
  app:
    image: php:8.3-apache
    container_name: yukifiles
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    command: bash -lc "sed -ri -e 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/*.conf /etc/apache2/apache2.conf && docker-php-ext-install pdo pdo_sqlite && apache2-foreground"
