services:
  - type: web
    name: yukifiles
    env: node
    plan: starter
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start:auto
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true